#!/bin/bash
OSM=$(cat /etc/*release | grep -o Ubuntu | wc -l) # Check for ubuntu distrib, If not, suppose Centos like.
Bapa="emacs git python3 -y"

if [ "$(id -u)" != "0" ]; then # Check for root
    echo "You must be root!"
    exit
fi

#        Additional functions (No packages):
#        [+] config: emacs file, .bashrc file
#        [+] hack: Install nmap, nmap script auto.

config () { # Ask for installing configuration files
    echo "Install config?"
    read E

    if [[ $E == [yY] ]]; then # Move configuration to respective directories.
	mv .emacs ~/
	if [[ $(grep '\\w\\a' ~/.bashrc | wc -l) == "1" ]]; then
	    bashrc=$(cat ~/.bashrc | sed '\\w\\a/\\W\\a') # Next version will add a better PS1!
	    rm ~/.bashrc
	    echo -e "$bashrc" > ~/.bashrc
	    source ~/.bashrc
	else
	    "Done"
	fi
    fi
    }

hack () { #Install hacking tools
    echo -e "Hacking tools?"
    read a

    if [[ $OSM == "Ubuntu" ]]; then
	if [[ $a == [yY] ]]; then
	    apt install nmap -y
	    mv -vf pport /usr/bin
	else
	    echo "Everything is installed!"
	fi
    else
	if [[ $a == [yY] ]]; then
	    yum install nmap -y
	else
	    echo "Everything is installed!"
	fi
    fi
mv -vf pport /usr/bin/
}



####################################################
################ INSTALLATION START ################
####################################################



if [[ $OSM == "Ubuntu" ]]; then ##Check if it's ubuntu or it's centos
    apt install $Bapa
    hack
    config
else
    yum install $Bapa
    config
fi

chmod +x sgit
mv -f sgit /usr/bin
