#!/bin/bash

if [[ -z "$1" ]]; then # Check if argument 1 exist.
    echo -e "You need at least one argument.
Usage for a normal scan: $0 IP
Usage for a fast scan with more info: $0 f IP"
    exit
fi

File=portlist
scan=$(echo $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

if [[ $scan == $1 ]]; then # Check if first argument is an ip.
    nmap $1 -p- -v -sV -sC --open -$2 -T4 -n -oG $File
elif [[ $1 == "f" ]]; then # Run a faster scan with more information.
    if [ "$(id -u)" != "0" ]; then # Check for root
	echo "To use this option please run as root (sudo)."
	exit
    fi
    nmap $2 -p- -sS -sV -sC --min-rate 5000 -v --open -n -Pn -oG $File
else
    echo -e "Usage for a normal scan: $0 IP
Usage for a fast scan with more info: $0 f IP"
    exit
fi

ip=$(cat $File | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u)
ports=$(cat $File | grep -oP '\d{1,5}/open' | awk '{print $1}' FS="/" | tr "\n" " ")

echo -e "\n\t\t [*] IP: $ip" > open_ports
echo -e "\t\t [*] PORTS: $ports\n" >> open_ports
cat open_ports
