#!/bin/bash
File=portlist
nmap $1 -p- -v --open -$2 -n -oG $File
ip=$(cat $File | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u)
ports=$(cat $File | grep -oP '\d{1,5}/open' | awk '{print $1}' FS="/" | tr "\n"  ", ")

echo -e "\n\t [*] IP: $ip" > open_ports
echo -e "\t [*] PORTS: $ports\n" >> open_ports
cat open_ports
