#!/bin/bash

echo -e "
         | ======================= |
         | ||||||||||||||||||||||| |
         | ||||||||||||||||||||||| |
         | || REMOVING PACKAGES || |
         | ||||||||||||||||||||||| |
         | ||||||||||||||||||||||| |
         | ======================= |
"

if [[ -z $1 ]]; then
   {
       echo "You need to put an argument!"
   }
fi

sudo apt remove $1 -y
sudo apt remove --auto-remove $1 -y
sudo apt purge $1 -y
sudo apt purge --auto-remove $1 -y
